### ISSUE TITLE
entrypoints.json Not Updated?

### ISSUE THREAD

**Issue by jonsq** [lcharette/UF_ConfigManager#12]
Fresh UF 5 installed on Windows.  

I followed your 3-step instructions, but received the following error when loading the settings page:

```Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template 
"Could not find the entry "page.config-manager" in "assets://entrypoints.json". 
Found: 
app, page.register, page.sign-in, page.forgot-password, page.resend-verification, page.set-or-reset-password, 
page.account-settings, dashboard, page.dashboard, page.activities, page.group, page.groups, page.role, page.roles, 
page.permission, page.permissions, page.user, page.users.
```

To fix this error I had to: 

1. Edit _"\public\assets\entrypoints.json"_ to include:
     ```javascript
    "page.config-manager": {
      "js": [
        "assets/js/ConfigManager.js"
      ]
    },
    "widget.formGenerator": {
      "js": [
        "assets/js/widget-formGenerator.js"
      ]
    }```
2.  I also copied both the "ConfigManager.js" and "widget-formGenerator.js" files to the _"\app\assets\js\"_ folder.


Did I make an obvious mistake somewhere that lead to this?

**Comment by lcharette** [comment]
I've updated the installation instructions on the README. The frontend assets were simply not installed. Let me know If it works.

**Comment by jonsq** [comment]
I reverted my previously mentioned changes and followed your new instructions.  It is now throwing the following error:
```
An exception has been thrown during the rendering of a template 

Could not find the entry "widget.formGenerator" in "assets://entrypoints.json". 

Found: 

app, page.register, page.sign-in, page.forgot-password, page.resend-verification, page.set-or-reset-password, 
page.account-settings, dashboard, page.dashboard, page.activities, page.group, page.groups, page.role, 
page.roles, page.permission, page.permissions, page.user, page.users, page.config-manager
```

**Comment by jonsq** [comment]
I was able to fix the **widget.formGenerator** error by:
1. Adding the following entry to webpack.config.js, in the const sprinkles list:
        `FormGenerator: require('@lcharette/formgenerator/webpack.entries'),`
2. And running **php bakery bake**.

**Comment by lcharette** [comment]
Yeah that make sense. I'll update the README again, or see if I can include FormGenerator entries with ConfigManager without breaking everything.

**Comment by jonsq** [comment]
Sounds good

**Comment by lcharette** [comment]
Done. Thanks !

**Comment by jonsq** [comment]
Looks good to me.
